[tool.black]
line-length = 120
target-version = ['py36', 'py37', 'py38']

[tool.isort]
profile = "black"
known_first_party = ["fpy"]
order_by_type = "False"
include_trailing_comma = "True"
multi_line_output = 3
use_parentheses = "True"